### ISSUE TITLE
Integrar com o CodeRhino

### ISSUE THREAD

**Issue by victor-torres** [Natalnet/W-Educ#30]

**Comment by sarinhaxp** [comment]
O projeto não vai mais utilizar applet. Em seu lugar será gerado um programa java genérico, que será enviado para o cliente e executado para que seja realiza a transmissão dos dados para o robô.

**Comment by victor-torres** [comment]
Legal, vão usar websocket?

**Comment by victor-torres** [comment]
@lucasalveslm pode estar desenvolvendo uma versão em Python dessa ideia.

**Comment by sarinhaxp** [comment]
Eu gero uma classe java para execução a partir do controler. E em seguida um jar, nele incluí os arquivos necessários para envio (nbc, avrdude ou afins) e o programa compilado. 
Aí o usuário baixa esse jar e quando ele o executa ele extrai apenas esses arquivos, em seguida roda o código de envio.
Foi a primeira solução que pensei como alternativa pra applet, fica bem leve.. Usei algumas das classes do CodeRhino para leitura e listagem de porta serial.

**Comment by victor-torres** [comment]
Legal, mas não é escalável. Imagine gerar diversas dessas classes toda vez que alguém compilar um programa. Acho que a solução do websocket seria a melhor opção. 

@lucasalveslm, já disponibilizou o código atualizado?

**Comment by lucasalveslm** [comment]
@victor-torres O código da aplicação python já está atualizado. Só tá faltando colocar o cliente javascript e fazer a documentação de como utilizar. Essa semana devo terminar.
